language: node_js
node_js:
   - "8.2.1"

before_script:
  - npm install

before_deploy:
  - npm run build
  - LAST_COMMIT=$(git log -1 --pretty=format:'%h <%an> - %s')
  - echo "Deploying changes from $LAST_COMMIT"
  - node_modules/gh-pages/bin/gh-pages -d dist/ -m "Updates from $LAST_COMMIT"

#deploy:
#  - npm run deploy
